// Mock de datos para la gestión de documentación de préstamos
export const documentationMock = {
  // Métricas principales
  summary: {
    totalLoans: 156,
    totalDocuments: 892,
    pendingDocuments: 23,
    totalSize: 2450000000, // 2.45 GB
    averageDocumentsPerLoan: 5.7,
    lastUpload: "2024-02-10T14:30:00Z",
  },

  // Documentos por estado
  byStatus: {
    complete: {
      count: 133,
      percentage: 85.3,
    },
    pending: {
      count: 23,
      percentage: 14.7,
    },
  },

  // Documentos por tipo
  byType: {
    identity: {
      count: 156,
      percentage: 17.5,
    },
    income: {
      count: 142,
      percentage: 15.9,
    },
    property: {
      count: 189,
      percentage: 21.2,
    },
    financial: {
      count: 167,
      percentage: 18.7,
    },
    legal: {
      count: 134,
      percentage: 15.0,
    },
    other: {
      count: 104,
      percentage: 11.7,
    },
  },

  // Lista de préstamos con documentación
  loans: [
    {
      id: "L001",
      clientName: "María González",
      loanType: "Hipotecario",
      amount: 3500000,
      status: "Aprobado",
      requestDate: "2024-01-10",
      documents: [
        {
          id: "D001",
          name: "DNI_Frente.pdf",
          type: "identity",
          category: "Identificación",
          size: 245760,
          uploadDate: "2024-01-12T10:30:00Z",
          uploadedBy: "María González",
          status: "Aprobado",
          version: "1.0",
          description: "Documento Nacional de Identidad - Frente",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D002",
          name: "DNI_Dorso.pdf",
          type: "identity",
          category: "Identificación",
          size: 198432,
          uploadDate: "2024-01-12T10:32:00Z",
          uploadedBy: "María González",
          status: "Aprobado",
          version: "1.0",
          description: "Documento Nacional de Identidad - Dorso",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D003",
          name: "Recibo_Sueldo_Enero.pdf",
          type: "income",
          category: "Ingresos",
          size: 156789,
          uploadDate: "2024-01-15T14:20:00Z",
          uploadedBy: "María González",
          status: "Aprobado",
          version: "1.0",
          description: "Recibo de sueldo del mes de enero",
          tags: ["Sueldo", "Ingresos", "Obligatorio"],
        },
        {
          id: "D004",
          name: "Titulo_Propiedad.pdf",
          type: "property",
          category: "Propiedad",
          size: 892456,
          uploadDate: "2024-01-18T09:15:00Z",
          uploadedBy: "María González",
          status: "Aprobado",
          version: "1.0",
          description: "Título de propiedad de la vivienda",
          tags: ["Propiedad", "Título", "Obligatorio"],
        },
        {
          id: "D005",
          name: "Avaluo_Propiedad.pdf",
          type: "property",
          category: "Propiedad",
          size: 1234567,
          uploadDate: "2024-01-20T16:45:00Z",
          uploadedBy: "María González",
          status: "Aprobado",
          version: "1.0",
          description: "Avalúo oficial de la propiedad",
          tags: ["Avalúo", "Propiedad", "Obligatorio"],
        },
      ],
    },
    {
      id: "L002",
      clientName: "Juan Pérez",
      loanType: "Garantía Recíproca",
      amount: 2800000,
      status: "Pendiente",
      requestDate: "2024-01-18",
      documents: [
        {
          id: "D006",
          name: "DNI_Completo.pdf",
          type: "identity",
          category: "Identificación",
          size: 445192,
          uploadDate: "2024-01-19T11:20:00Z",
          uploadedBy: "Juan Pérez",
          status: "Aprobado",
          version: "1.0",
          description: "DNI completo (frente y dorso)",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D007",
          name: "Balance_Empresa.xlsx",
          type: "financial",
          category: "Financiero",
          size: 234567,
          uploadDate: "2024-01-22T13:10:00Z",
          uploadedBy: "Juan Pérez",
          status: "Pendiente",
          version: "1.0",
          description: "Balance de la empresa de los últimos 2 años",
          tags: ["Balance", "Empresa", "Obligatorio"],
        },
        {
          id: "D008",
          name: "Certificado_Ingresos.pdf",
          type: "income",
          category: "Ingresos",
          size: 98765,
          uploadDate: "2024-01-25T15:30:00Z",
          uploadedBy: "Juan Pérez",
          status: "Pendiente",
          version: "1.0",
          description: "Certificado de ingresos emitido por contador",
          tags: ["Ingresos", "Certificado", "Obligatorio"],
        },
      ],
    },
    {
      id: "L003",
      clientName: "Ana Martínez",
      loanType: "Hipotecario",
      amount: 4200000,
      status: "Aprobado",
      requestDate: "2024-01-22",
      documents: [
        {
          id: "D009",
          name: "DNI_Frente_Ana.pdf",
          type: "identity",
          category: "Identificación",
          size: 267890,
          uploadDate: "2024-01-23T08:45:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "DNI - Frente",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D010",
          name: "DNI_Dorso_Ana.pdf",
          type: "identity",
          category: "Identificación",
          size: 245678,
          uploadDate: "2024-01-23T08:47:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "DNI - Dorso",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D011",
          name: "Recibos_Sueldo_6meses.pdf",
          type: "income",
          category: "Ingresos",
          size: 3456789,
          uploadDate: "2024-01-26T12:15:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "Recibos de sueldo de los últimos 6 meses",
          tags: ["Sueldo", "Ingresos", "Obligatorio"],
        },
        {
          id: "D012",
          name: "Titulo_Propiedad_Ana.pdf",
          type: "property",
          category: "Propiedad",
          size: 1234567,
          uploadDate: "2024-01-28T10:30:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "Título de propiedad",
          tags: ["Propiedad", "Título", "Obligatorio"],
        },
        {
          id: "D013",
          name: "Avaluo_Propiedad_Ana.pdf",
          type: "property",
          category: "Propiedad",
          size: 1567890,
          uploadDate: "2024-01-30T14:20:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "Avalúo oficial de la propiedad",
          tags: ["Avalúo", "Propiedad", "Obligatorio"],
        },
        {
          id: "D014",
          name: "Historial_Crediticio.pdf",
          type: "financial",
          category: "Financiero",
          size: 456789,
          uploadDate: "2024-02-01T09:45:00Z",
          uploadedBy: "Ana Martínez",
          status: "Aprobado",
          version: "1.0",
          description: "Historial crediticio de los últimos 5 años",
          tags: ["Crédito", "Historial", "Obligatorio"],
        },
      ],
    },
    {
      id: "L004",
      clientName: "Roberto Silva",
      loanType: "Garantía Recíproca",
      amount: 1800000,
      status: "Pendiente",
      requestDate: "2024-01-25",
      documents: [
        {
          id: "D015",
          name: "DNI_Roberto.pdf",
          type: "identity",
          category: "Identificación",
          size: 398765,
          uploadDate: "2024-01-26T16:20:00Z",
          uploadedBy: "Roberto Silva",
          status: "Aprobado",
          version: "1.0",
          description: "DNI completo",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D016",
          name: "Plan_Negocio.pdf",
          type: "other",
          category: "Otros",
          size: 2345678,
          uploadDate: "2024-01-29T11:30:00Z",
          uploadedBy: "Roberto Silva",
          status: "Pendiente",
          version: "1.0",
          description: "Plan de negocio detallado",
          tags: ["Negocio", "Plan", "Opcional"],
        },
      ],
    },
    {
      id: "L005",
      clientName: "Laura Fernández",
      loanType: "Hipotecario",
      amount: 3200000,
      status: "Aprobado",
      requestDate: "2024-01-28",
      documents: [
        {
          id: "D017",
          name: "DNI_Laura.pdf",
          type: "identity",
          category: "Identificación",
          size: 412345,
          uploadDate: "2024-01-29T13:15:00Z",
          uploadedBy: "Laura Fernández",
          status: "Aprobado",
          version: "1.0",
          description: "DNI completo",
          tags: ["DNI", "Identificación", "Obligatorio"],
        },
        {
          id: "D018",
          name: "Recibos_Sueldo_Laura.pdf",
          type: "income",
          category: "Ingresos",
          size: 2987654,
          uploadDate: "2024-02-01T10:45:00Z",
          uploadedBy: "Laura Fernández",
          status: "Aprobado",
          version: "1.0",
          description: "Recibos de sueldo de los últimos 12 meses",
          tags: ["Sueldo", "Ingresos", "Obligatorio"],
        },
        {
          id: "D019",
          name: "Titulo_Propiedad_Laura.pdf",
          type: "property",
          category: "Propiedad",
          size: 987654,
          uploadDate: "2024-02-03T15:20:00Z",
          uploadedBy: "Laura Fernández",
          status: "Aprobado",
          version: "1.0",
          description: "Título de propiedad",
          tags: ["Propiedad", "Título", "Obligatorio"],
        },
        {
          id: "D020",
          name: "Avaluo_Laura.pdf",
          type: "property",
          category: "Propiedad",
          size: 1345678,
          uploadDate: "2024-02-05T12:30:00Z",
          uploadedBy: "Laura Fernández",
          status: "Aprobado",
          version: "1.0",
          description: "Avalúo oficial",
          tags: ["Avalúo", "Propiedad", "Obligatorio"],
        },
      ],
    },
  ],

  // Tipos de documentos disponibles
  documentTypes: [
    {
      id: "identity",
      name: "Identificación",
      required: true,
      description: "Documentos de identidad del cliente",
      examples: ["DNI", "Pasaporte", "Cédula"],
    },
    {
      id: "income",
      name: "Ingresos",
      required: true,
      description: "Comprobantes de ingresos y capacidad de pago",
      examples: [
        "Recibos de sueldo",
        "Certificados de ingresos",
        "Declaraciones juradas",
      ],
    },
    {
      id: "property",
      name: "Propiedad",
      required: true,
      description: "Documentación relacionada con la propiedad",
      examples: ["Título de propiedad", "Avalúo", "Plano de la propiedad"],
    },
    {
      id: "financial",
      name: "Financiero",
      required: true,
      description: "Documentación financiera y crediticia",
      examples: ["Balance", "Historial crediticio", "Estados de cuenta"],
    },
    {
      id: "legal",
      name: "Legal",
      required: false,
      description: "Documentación legal y contractual",
      examples: ["Contratos", "Escrituras", "Poderes"],
    },
    {
      id: "other",
      name: "Otros",
      required: false,
      description: "Documentación adicional",
      examples: ["Plan de negocio", "Referencias", "Otros comprobantes"],
    },
  ],

  // Alertas del sistema
  alerts: [
    {
      id: 1,
      type: "warning",
      title: "Documentos pendientes",
      message: "23 préstamos tienen documentación incompleta",
      count: 23,
      priority: "high",
    },
    {
      id: 2,
      type: "info",
      title: "Nuevas subidas",
      message: "15 documentos subidos en las últimas 24 horas",
      count: 15,
      priority: "medium",
    },
    {
      id: 3,
      type: "success",
      title: "Documentación completada",
      message: "8 préstamos completaron su documentación",
      count: 8,
      priority: "low",
    },
  ],

  // Configuración de archivos
  fileConfig: {
    maxFileSize: 10485760, // 10MB
    allowedTypes: [
      ".pdf",
      ".jpg",
      ".jpeg",
      ".png",
      ".doc",
      ".docx",
      ".xls",
      ".xlsx",
    ],
    maxFilesPerLoan: 20,
    autoRename: true,
    versionControl: true,
  },
};
