// Mock de datos para la gestión de garantías recíprocas
export const guaranteesMock = {
  // Métricas principales
  summary: {
    totalGuarantees: 156,
    activeGuarantees: 142,
    pendingApproval: 14,
    totalAmount: 23450000,
    approvedAmount: 19800000,
    pendingAmount: 3650000,
    averageProcessingTime: 3.2,
    approvalRate: 89.7,
  },

  // Garantías por estado
  byStatus: {
    approved: {
      count: 142,
      amount: 19800000,
      percentage: 91.0,
    },
    pending: {
      count: 14,
      amount: 3650000,
      percentage: 9.0,
    },
  },

  // Garantías por tipo de empresa
  byCompanyType: {
    pyme: {
      count: 89,
      amount: 12500000,
      percentage: 57.1,
    },
    microempresa: {
      count: 45,
      amount: 6800000,
      percentage: 29.0,
    },
    cooperativa: {
      count: 22,
      amount: 4150000,
      percentage: 13.9,
    },
  },

  // Lista de garantías
  guarantees: [
    {
      id: "G001",
      companyName: "Constructora del Norte S.A.",
      companyType: "PYME",
      requestDate: "2024-01-15",
      amount: 2500000,
      purpose: "Expansión de planta industrial",
      status: "approved",
      approvedDate: "2024-01-18",
      approvedBy: "María González",
      riskScore: 85,
      documents: ["Balance 2023", "Flujo de caja", "Plan de negocio"],
      notes: "Empresa con buen historial crediticio",
      processingTime: 3,
    },
    {
      id: "G002",
      companyName: "Tecnología Avanzada Ltda.",
      companyType: "PYME",
      requestDate: "2024-01-20",
      amount: 1800000,
      purpose: "Compra de equipamiento tecnológico",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 72,
      documents: ["Balance 2023", "Proyecciones financieras"],
      notes: "Pendiente revisión de documentación adicional",
      processingTime: 2,
    },
    {
      id: "G003",
      companyName: "Comercial del Sur S.A.",
      companyType: "Microempresa",
      requestDate: "2024-01-22",
      amount: 800000,
      purpose: "Capital de trabajo",
      status: "approved",
      approvedDate: "2024-01-25",
      approvedBy: "Carlos Rodríguez",
      riskScore: 78,
      documents: ["Balance 2023", "Declaraciones impositivas"],
      notes: "Empresa estable con crecimiento sostenido",
      processingTime: 3,
    },
    {
      id: "G004",
      companyName: "Cooperativa Agrícola La Esperanza",
      companyType: "Cooperativa",
      requestDate: "2024-01-25",
      amount: 1200000,
      purpose: "Compra de maquinaria agrícola",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 68,
      documents: ["Balance 2023", "Certificados de producción"],
      notes: "Requiere evaluación de capacidad de pago",
      processingTime: 1,
    },
    {
      id: "G005",
      companyName: "Servicios Industriales Este S.A.",
      companyType: "PYME",
      requestDate: "2024-01-28",
      amount: 3200000,
      purpose: "Modernización de equipos",
      status: "approved",
      approvedDate: "2024-01-30",
      approvedBy: "Ana Martínez",
      riskScore: 92,
      documents: ["Balance 2023", "Estados financieros", "Plan de inversión"],
      notes: "Excelente perfil crediticio y proyecciones",
      processingTime: 2,
    },
    {
      id: "G006",
      companyName: "Distribuidora Central Ltda.",
      companyType: "Microempresa",
      requestDate: "2024-01-30",
      amount: 650000,
      purpose: "Ampliación de local comercial",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 65,
      documents: ["Balance 2023", "Contrato de alquiler"],
      notes: "Pendiente documentación de propiedad",
      processingTime: 1,
    },
    {
      id: "G007",
      companyName: "Cooperativa de Vivienda Progreso",
      companyType: "Cooperativa",
      requestDate: "2024-02-01",
      amount: 2800000,
      purpose: "Construcción de viviendas sociales",
      status: "approved",
      approvedDate: "2024-02-03",
      approvedBy: "Luis Fernández",
      riskScore: 88,
      documents: [
        "Balance 2023",
        "Proyecto arquitectónico",
        "Permisos municipales",
      ],
      notes: "Proyecto social con respaldo gubernamental",
      processingTime: 2,
    },
    {
      id: "G008",
      companyName: "Metalúrgica del Oeste S.A.",
      companyType: "PYME",
      requestDate: "2024-02-05",
      amount: 4500000,
      purpose: "Instalación de nueva línea de producción",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 75,
      documents: [
        "Balance 2023",
        "Estudio de mercado",
        "Análisis de viabilidad",
      ],
      notes: "Proyecto ambicioso, requiere análisis detallado",
      processingTime: 2,
    },
  ],

  // Alertas del sistema
  alerts: [
    {
      id: 1,
      type: "warning",
      title: "Garantías pendientes de revisión",
      message: "14 garantías requieren atención inmediata",
      count: 14,
      amount: 3650000,
    },
    {
      id: 2,
      type: "info",
      title: "Nuevas solicitudes",
      message: "5 nuevas solicitudes recibidas hoy",
      count: 5,
      amount: 1200000,
    },
    {
      id: 3,
      type: "success",
      title: "Garantías aprobadas",
      message: "8 garantías aprobadas esta semana",
      count: 8,
      amount: 15600000,
    },
  ],

  // Métricas de rendimiento
  performance: {
    averageProcessingTime: 3.2,
    approvalRate: 89.7,
    averageRiskScore: 78.5,
    totalProcessed: 156,
    totalApproved: 142,
    totalRejected: 14,
  },

  // Filtros disponibles
  filters: {
    statuses: ["Todos", "Aprobadas", "Pendientes", "Rechazadas"],
    companyTypes: ["Todos", "PYME", "Microempresa", "Cooperativa"],
    riskRanges: ["Todos", "Alto (0-60)", "Medio (61-80)", "Bajo (81-100)"],
    amountRanges: ["Todos", "0-500k", "500k-1M", "1M-2M", "2M+"],
  },
};
