// Mock de datos para la gestión de hipotecas
export const mortgagesMock = {
  // Métricas principales
  summary: {
    totalMortgages: 89,
    activeMortgages: 76,
    pendingApproval: 13,
    totalAmount: 45600000,
    approvedAmount: 38900000,
    pendingAmount: 6700000,
    averageProcessingTime: 4.1,
    approvalRate: 85.4,
  },

  // Hipotecas por estado
  byStatus: {
    approved: {
      count: 75,
      amount: 38900000,
      percentage: 85.4,
    },
    pending: {
      count: 13,
      amount: 6700000,
      percentage: 14.6,
    },
  },

  // Hipotecas por tipo de propiedad
  byPropertyType: {
    casa: {
      count: 45,
      amount: 23400000,
      percentage: 50.6,
    },
    departamento: {
      count: 32,
      amount: 15600000,
      percentage: 36.0,
    },
    terreno: {
      count: 12,
      amount: 6600000,
      percentage: 13.4,
    },
  },

  // Lista de hipotecas
  mortgages: [
    {
      id: "H001",
      clientName: "María González",
      propertyType: "Casa",
      propertyAddress: "Av. San Martín 1234, CABA",
      requestDate: "2024-01-10",
      amount: 3500000,
      purpose: "Compra de vivienda familiar",
      status: "approved",
      approvedDate: "2024-01-15",
      approvedBy: "Carlos Rodríguez",
      riskScore: 88,
      documents: [
        "Título de propiedad",
        "Avalúo",
        "Ingresos comprobables",
        "Historial crediticio",
      ],
      notes: "Excelente perfil crediticio, propiedad bien ubicada",
      processingTime: 5,
      propertyValue: 4200000,
      downPayment: 700000,
      loanTerm: 20,
      interestRate: 12.5,
    },
    {
      id: "H002",
      clientName: "Juan Pérez",
      propertyType: "Departamento",
      propertyAddress: "Belgrano 567, CABA",
      requestDate: "2024-01-18",
      amount: 2800000,
      purpose: "Compra de departamento para inversión",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 72,
      documents: ["Título de propiedad", "Avalúo", "Ingresos comprobables"],
      notes: "Pendiente documentación adicional de ingresos",
      processingTime: 3,
      propertyValue: 3200000,
      downPayment: 400000,
      loanTerm: 15,
      interestRate: 13.2,
    },
    {
      id: "H003",
      clientName: "Ana Martínez",
      propertyType: "Casa",
      propertyAddress: "Vicente López 890, Provincia",
      requestDate: "2024-01-22",
      amount: 4200000,
      purpose: "Compra de casa para familia numerosa",
      status: "approved",
      approvedDate: "2024-01-28",
      approvedBy: "María González",
      riskScore: 92,
      documents: [
        "Título de propiedad",
        "Avalúo",
        "Ingresos comprobables",
        "Historial crediticio",
        "Certificado de ingresos",
      ],
      notes: "Perfil excelente, propiedad de alto valor",
      processingTime: 6,
      propertyValue: 4800000,
      downPayment: 600000,
      loanTerm: 25,
      interestRate: 11.8,
    },
    {
      id: "H004",
      clientName: "Roberto Silva",
      propertyType: "Terreno",
      propertyAddress: "Ruta 2 Km 45, La Plata",
      requestDate: "2024-01-25",
      amount: 1800000,
      purpose: "Compra de terreno para construcción futura",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 65,
      documents: ["Título de propiedad", "Avalúo"],
      notes: "Requiere evaluación de capacidad de pago",
      processingTime: 2,
      propertyValue: 2000000,
      downPayment: 200000,
      loanTerm: 10,
      interestRate: 14.5,
    },
    {
      id: "H005",
      clientName: "Laura Fernández",
      propertyType: "Departamento",
      propertyAddress: "Palermo 123, CABA",
      requestDate: "2024-01-28",
      amount: 3200000,
      purpose: "Compra de departamento para vivir",
      status: "approved",
      approvedDate: "2024-02-02",
      approvedBy: "Ana Martínez",
      riskScore: 85,
      documents: [
        "Título de propiedad",
        "Avalúo",
        "Ingresos comprobables",
        "Historial crediticio",
      ],
      notes: "Buena ubicación, perfil crediticio estable",
      processingTime: 5,
      propertyValue: 3600000,
      downPayment: 400000,
      loanTerm: 18,
      interestRate: 12.8,
    },
    {
      id: "H006",
      clientName: "Carlos López",
      propertyType: "Casa",
      propertyAddress: "San Isidro 456, Provincia",
      requestDate: "2024-02-01",
      amount: 5500000,
      purpose: "Compra de casa de lujo",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 78,
      documents: ["Título de propiedad", "Avalúo", "Ingresos comprobables"],
      notes: "Propiedad de alto valor, requiere análisis detallado",
      processingTime: 4,
      propertyValue: 6200000,
      downPayment: 700000,
      loanTerm: 20,
      interestRate: 12.0,
    },
    {
      id: "H007",
      clientName: "Patricia Ruiz",
      propertyType: "Departamento",
      propertyAddress: "Recoleta 789, CABA",
      requestDate: "2024-02-05",
      amount: 3800000,
      purpose: "Compra de departamento para alquiler",
      status: "approved",
      approvedDate: "2024-02-08",
      approvedBy: "Carlos Rodríguez",
      riskScore: 90,
      documents: [
        "Título de propiedad",
        "Avalúo",
        "Ingresos comprobables",
        "Historial crediticio",
        "Plan de inversión",
      ],
      notes: "Excelente ubicación, potencial de renta alto",
      processingTime: 3,
      propertyValue: 4200000,
      downPayment: 400000,
      loanTerm: 15,
      interestRate: 12.2,
    },
    {
      id: "H008",
      clientName: "Miguel Torres",
      propertyType: "Terreno",
      propertyAddress: "Pilar 321, Provincia",
      requestDate: "2024-02-08",
      amount: 1200000,
      purpose: "Compra de terreno para casa de fin de semana",
      status: "pending",
      approvedDate: null,
      approvedBy: null,
      riskScore: 68,
      documents: ["Título de propiedad", "Avalúo", "Ingresos comprobables"],
      notes: "Propósito recreativo, requiere evaluación adicional",
      processingTime: 2,
      propertyValue: 1400000,
      downPayment: 200000,
      loanTerm: 12,
      interestRate: 13.8,
    },
  ],

  // Alertas del sistema
  alerts: [
    {
      id: 1,
      type: "warning",
      title: "Hipotecas pendientes de revisión",
      message: "13 hipotecas requieren atención inmediata",
      count: 13,
      amount: 6700000,
    },
    {
      id: 2,
      type: "info",
      title: "Nuevas solicitudes",
      message: "3 nuevas solicitudes recibidas hoy",
      count: 3,
      amount: 8500000,
    },
    {
      id: 3,
      type: "success",
      title: "Hipotecas aprobadas",
      message: "5 hipotecas aprobadas esta semana",
      count: 5,
      amount: 18700000,
    },
  ],

  // Métricas de rendimiento
  performance: {
    averageProcessingTime: 4.1,
    approvalRate: 85.4,
    averageRiskScore: 79.8,
    totalProcessed: 89,
    totalApproved: 76,
    totalRejected: 13,
  },

  // Filtros disponibles
  filters: {
    statuses: ["Todos", "Aprobadas", "Pendientes", "Rechazadas"],
    propertyTypes: ["Todos", "Casa", "Departamento", "Terreno"],
    riskRanges: ["Todos", "Alto (0-60)", "Medio (61-80)", "Bajo (81-100)"],
    amountRanges: ["Todos", "0-1M", "1M-2M", "2M-3M", "3M+"],
  },
};
