export const adaptNewRelationData = (data) => {
  const adaptedData = {
    clientId: data.idClient,
    name: data.name,
    lastName: data.lastName,
    businessName: data.bussinessName,
    passport: data.passport,
    cuit: data.cuit,
    nationality: data.nationality,
    street: data.street,
    streetNumber: data.numberStreet,
    city: data.city,
    postalCode: data.postalCode,
    email: data.email,
    cellPhone: data.cellPhone,
    facebookId: data.facebookId,
    googleId: data.googleId,
    appleId: data.appleId,
    otherId: data.otherId,
    verified: data.verified,
    level: data.level,
    category: data.category,
    use: data.use,
    civilStatusId: data.civilstatusId,
    genderId: data.genreId,
    floor: data.floor,
    department: data.departament,
    origin: data.origin,
    originId: data.idOrigin,
    birthDate: data.birthDate,
    residence: data.residence,
    birthPlace: data.birthPlace,
    reference: data.reference,
    profession: data.profession,
    position: data.position,
    relationId: data.idRelation,
    status: data.status,
    participation: data.participation,
  };

  return adaptedData;
};
