export default {
  "suppliers" : [
    {
        "id": 12,
        "cuit": "23330242434",
        "business_name": "CAMILA OEYEN",
        "country": "+54",
        "province": "Buenos Aires",
        "city": "caba",
        "address": "corrientes 123",
        "cp": "1425",
        "cellphone": "+5491124512589",
        "email": "test@test.com.bc",
        "category_id": 1,
        "center_id": 13,
        "status": 1
    },
    {
        "id": 14,
        "cuit": "20397182097",
        "business_name": "Claudio Gomez",
        "country": "Argentina",
        "province": "Buenos Aires",
        "city": "Mar del Plata",
        "address": "Roca 123 piso 1 depto 3",
        "cp": "1414A",
        "cellphone": "+5411606060",
        "email": "claudio.gomez@example.com",
        "category_id": 97,
        "center_id": 14,
        "status": 1
    },
    {
        "id": 15,
        "cuit": "20278568777",
        "business_name": "LUCAS RUBEN GAVILAN LUCAS RUB N",
        "country": "+54",
        "province": "Buenos Aires",
        "city": "caba",
        "address": "corrientes 123",
        "cp": "1425",
        "cellphone": "+5491124512589",
        "email": "data@myhnt.com.ar",
        "category_id": 97,
        "center_id": 14,
        "status": 1
    },
    {
        "id": 17,
        "cuit": "20311767365",
        "business_name": "Lucas Levy",
        "country": "Argentina",
        "province": "Buenos Aires",
        "city": "Mar del Plata",
        "address": "Roca 123 piso 1 depto 3",
        "cp": "1414A",
        "cellphone": "+5411606060",
        "email": "claudio.gomez@example.com",
        "category_id": 49,
        "center_id": 14,
        "status": 1
    },
    {
        "id": 18,
        "cuit": "20941404627",
        "business_name": "JOSHUA NICOLAS CANDIA RICO",
        "country": "+54",
        "province": "Buenos Aires",
        "city": "caba",
        "address": "corrientes 123",
        "cp": "1425",
        "cellphone": "+5491124512589",
        "email": "data@myhnt.com.ar",
        "category_id": 97,
        "center_id": 14,
        "status": 1
    },
    {
        "id": 19,
        "cuit": "20272910694",
        "business_name": "Gonzalo Muller",
        "country": "Argentina",
        "province": "Buenos Aires",
        "city": "Mar del Plata",
        "address": "Roca 123 piso 1 depto 3",
        "cp": "1414A",
        "cellphone": "+5411606060",
        "email": "Gonzalo.muller@example.com",
        "category_id": 49,
        "center_id": 14,
        "status": 1
    }
]
}